development: &default
<% if defined?(JRUBY_VERSION) %>
<% adapter = java.lang.System.getProperty('kaui.db.adapter', 'mysql2') %>
  adapter: <%= adapter %>
  encoding: <%= java.lang.System.getProperty('kaui.db.encoding', 'utf8') %>
<% if adapter == 'sqlite3' %>
  database: <%= java.lang.System.getProperty('kaui.db.database', '/var/tmp/kaui.sqlite3') %>
  pool: 50
  timeout: 5000
<% else %>
  url: <%= java.lang.System.getProperty('kaui.db.url', 'jdbc:mysql://localhost:3306/kaui?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC') %>
  username: <%= java.lang.System.getProperty('kaui.db.username', 'root') %>
  password: <%= java.lang.System.getProperty('kaui.db.password', 'root') %>
  host: <%= java.lang.System.getProperty('kaui.db.host') %>
  port: <%= java.lang.System.getProperty('kaui.db.port') %>
  pool: <%= java.lang.System.getProperty('kaui.db.pool', '50') %>
  timeout: <%= java.lang.System.getProperty('kaui.db.timeout', '5000') %>
<% end %>
<% else %>
  adapter: mysql2
  encoding: utf8
  database: kaui
  username: root
  password: root
  host: 127.0.0.1
  port: 3306
  pool: 50
  timeout: 5000
<% end %>

# Warning: The database defined as "test" will be erased and
# re-generated from your development database when you run "rake".
# Do not set this db to the same as development or production.
test:
  adapter: sqlite3
  database: db/test.sqlite3

production:
  <<: *default
